# Generated by Django 5.0.2 on 2024-02-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Добавить напаравление',
                'verbose_name_plural': 'Добавить напаравление',
            },
        ),
    ]
