# Generated by Django 5.0.2 on 2024-02-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название статуса')),
            ],
            options={
                'verbose_name': 'Добавить Статусы',
                'verbose_name_plural': 'Добавить Статус',
            },
        ),
    ]
