# Generated by Django 5.0.2 on 2024-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.FloatField(default=0, verbose_name='Баллы'),
        ),
    ]
