# Generated by Django 5.0.2 on 2024-02-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_status'),
        ('telegram_bot', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': ' Пользователь телеграм', 'verbose_name_plural': ' Пользователи телеграма'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '1) Студенты', 'verbose_name_plural': '1) Студенты'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Чат ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secondary.status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary.nap', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='ID пользователя telegram'),
        ),
    ]
