# Generated by Django 5.0.2 on 2024-02-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_status'),
        ('telegram_bot', '0006_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secondary.status', verbose_name='Статус'),
        ),
    ]
