# Generated by Django 5.0.2 on 2024-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_userprofile_interview_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.FloatField(default=0.0, verbose_name='Общий счет баллов'),
        ),
    ]
